In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
# define Regula Falsi Method : 

def RFM(f,x:list,max_itr:int=100,tol:float=1e-6): 
    """
        param f: Callable function to apply the algorithm on. 
        param x: list of lenght 2 containaing the initial gusees a and b 
        param max_itr: max iteration the algorithm should run for. 
        param tol: tolerance upto wich the algorithm should run. 
    """
    
    # Verify if the params are valid : 
    if(len(x)!=2): 
        raise ValueError('x must be a list of length 2')
    a0 , b0 = x 
    if( a0 >= b0 ): 
        raise ValueError('x[0] must be strictly smaller than x[1]')
    if( f(a0)*f(b0) >=0 ): 
        raise ValueError('The function must have different signs at points a and b.')
    
    a , b , w  = [a0] , [b0] , [( a0*f(b0) - b0*f(a0) )/( f(b0) - f(a0) ) ] 
    fw = [f(w[-1])]
    # run the loop : 
    itr = 1 
    while itr < max_itr  and abs( fw[-1] ) > tol :
        if( fw[-1]*f(a[-1]) < 0 ): 
            a.append( a[-1] )
            b.append( w[-1] )
        else :
            a.append( w[-1] )
            b.append( b[-1] )
        w.append( (a[-1]*f(b[-1]) - b[-1]*f(a[-1]) )/( f(b[-1])- f(a[-1]) ) )
        fw.append( f(w[-1]) )
        itr += 1 
    
    if( itr == max_itr ): 
        print('----------Reached Max Iterations----------')
    # stack together the list to form a data matrix
    data = np.stack( (a,b,w,fw) , axis = 1 )
    # convert the matrix into pandas data frame 
    data = pd.DataFrame( data , columns=['a','b','w','f(w)'])
    return w[-1] , data

In [3]:
# define Regula Falsi Method : 

def MRFM(f,x:list,max_itr:int=100,tol:float=1e-6): 
    """
        param f: Callable function to apply the algorithm on. 
        param x: list of lenght 2 containaing the initial gusees a and b 
        param max_itr: max iteration the algorithm should run for. 
        param tol: tolerance upto wich the algorithm should run. 
    """
    
    # Verify if the params are valid : 
    if(len(x)!=2): 
        raise ValueError('x must be a list of length 2')
    a0 , b0 = x 
    if( a0 >= b0 ): 
        raise ValueError('x[0] must be strictly smaller than x[1]')
    if( f(a0)*f(b0) >=0 ): 
        raise ValueError('The function must have different signs at points a and b.')
    
    a , b , w  = [a0] , [b0] , [( a0*f(b0) - b0*f(a0) )/( f(b0) - f(a0) ) ] 
    fw = [f(w[-1])]
    slope = [ f(a0) , f(b0) ]
    c , z = 0 , 0 
    # run the loop : 
    itr = 1 
    while itr < max_itr  and abs( fw[-1] ) > tol : 
        if( fw[-1]*f(a[-1]) < 0 ): 
            a.append( a[-1] )
            b.append( w[-1] )
            slope[1] = fw[-1]
            c , z = c + 1 , 0 
        else :
            a.append( w[-1] )
            b.append( b[-1] )
            slope[0] = fw[-1]
            c , z = 0 , z + 1 
        if len(w) > 1 and c >= 2 : 
            slope[0] /= 2 
        if len(w) > 1 and z >= 2 : 
            slope[1] /= 2 
        w.append((a[-1]*slope[1]- b[-1]*slope[0])/(slope[1]-slope[0]))
        fw.append( f(w[-1]) )
        itr += 1 
    
    if( itr == max_itr ): 
        print('----------Reached Max Iterations----------')
    # stack together the list to form a data matrix
    data = np.stack( (a,b,w,fw) , axis = 1 )
    # convert the matrix into pandas data frame 
    data = pd.DataFrame( data , columns=['a','b','w','f(w)'])
    return w[-1] , data

In [4]:
# define Regula Falsi Method : 

def SM(f,x:list,max_itr:int=100,tol:float=1e-5): 
    """
        param f: Callable function to apply the algorithm on. 
        param x: list of lenght 2 containaing the initial gusees a and b 
        param max_itr: max iteration the algorithm should run for. 
        param tol: tolerance upto wich the algorithm should run. 
    """
    
    # Verify if the params are valid : 
    if(len(x)!=2): 
        raise ValueError('x must be a list of length 2')
    a0 , b0 = x 
    
    a , b , w  = [a0] , [b0] , [( a0*f(b0) - b0*f(a0) )/( f(b0) - f(a0) )] 
    fw = [f(w[-1])]
    # run the loop : 
    itr = 1 
    while itr < max_itr  and abs( fw[-1] ) > tol :
        a.append( b[-1] )
        b.append( w[-1] )
        w.append( (a[-1]*f(b[-1]) - b[-1]*f(a[-1]) )/( f(b[-1])- f(a[-1]) ) )
        fw.append( f(w[-1]) )
        itr += 1 
    
    if( itr == max_itr ): 
        print('----------Reached Max Iterations----------')
    # stack together the list to form a data matrix
    data = np.stack( (a,b,w,fw) , axis = 1 )
    # convert the matrix into pandas data frame 
    data = pd.DataFrame( data , columns=['Xn-1','Xn','Xn+1','f(Xn+1)'])
    return w[-1] , data

In [5]:
# define Regula Falsi Method : 

def NRM(f,f1,x,max_itr:int=100,tol:float=3e-7): 
    """
        param f: Callable function to apply the algorithm on. 
        param x: list of lenght 2 containaing the initial gusees a and b 
        param max_itr: max iteration the algorithm should run for. 
        param tol: tolerance upto wich the algorithm should run. 
    """
    
    a , w  = [x] , [x - f(x)/f1(x)] 
    fw = [f(w[-1])]
    # run the loop : 
    itr = 1 
    while itr < max_itr  and abs( fw[-1] ) > tol :
        a.append( w[-1] )
        w.append( a[-1] - f(a[-1])/f1(a[-1]) )
        fw.append( f(w[-1]) )
        itr += 1 
    
    if( itr == max_itr ): 
        print('----------Reached Max Iterations----------')
    # stack together the list to form a data matrix
    data = np.stack( (a,w,fw) , axis = 1 )
    # convert the matrix into pandas data frame 
    data = pd.DataFrame( data , columns=['Xn','Xn+1','f(Xn+1)'])
    return w[-1] , data

In [6]:
f = lambda x : 2*(x**3) - 2.5*x - 5 
x = [ 1.0 , 2.0 ]

In [7]:
_ , data = RFM(f,x)
data.to_excel('Results/RFM.xlsx' , index_label='Iteration')
data

           a    b         w          f(w)
0   1.000000  2.0  1.478261 -2.234898e+00
1   1.478261  2.0  1.619857 -5.488317e-01
2   1.619857  2.0  1.651716 -1.169839e-01
3   1.651716  2.0  1.658376 -2.416586e-02
4   1.658376  2.0  1.659747 -4.959566e-03
5   1.659747  2.0  1.660028 -1.016488e-03
6   1.660028  2.0  1.660085 -2.082770e-04
7   1.660085  2.0  1.660097 -4.267327e-05
8   1.660097  2.0  1.660100 -8.743100e-06
9   1.660100  2.0  1.660100 -1.791323e-06
10  1.660100  2.0  1.660100 -3.670137e-07

In [8]:
_ , data = MRFM(f,x)
data.to_excel('Results/MRFM.xlsx', index_label='Iteration')
data

          a         b         w          f(w)
0  1.000000  2.000000  1.478261 -2.234898e+00
1  1.478261  2.000000  1.619857 -5.488317e-01
2  1.619857  2.000000  1.678647  2.637533e-01
3  1.619857  1.678647  1.659565 -7.513505e-03
4  1.659565  1.678647  1.660093 -9.802992e-05
5  1.660093  1.678647  1.660107  9.540260e-05
6  1.660093  1.660107  1.660100 -4.728715e-10

In [9]:
_ , data = SM(f,x)
data.to_excel("Results/SM.xlsx", index_label='Iteration')
data

       Xn-1        Xn      Xn+1   f(Xn+1)
0  1.000000  2.000000  1.478261 -2.234898
1  2.000000  1.478261  1.619857 -0.548832
2  1.478261  1.619857  1.665949  0.082425
3  1.619857  1.665949  1.659930 -0.002386
4  1.665949  1.659930  1.660100 -0.000010

In [11]:
f1 = lambda x : 6*(x**2) - 2.5 
_ , data = NRM(f,f1,2)
data.to_excel("Results/NRM.xlsx", index_label='Iteration')
data

         Xn      Xn+1       f(Xn+1)
0  2.000000  1.720930  8.910914e-01
1  1.720930  1.662573  3.476693e-02
2  1.662573  1.660105  6.074948e-05
3  1.660105  1.660100  1.865974e-10